/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    static int[] roll (int n) {
        Random rnd = new Random();
        int dice[] = new int[n];
        for (int i = 0; i < n; i++) {
            dice[i] = rnd.nextInt(6) + 1;
        }
        return dice;
    }

    static boolean containsDuplicates (int[] arr) {
        int currItem;
        for (int i = 0; i < arr.length; i++) {
            currItem = arr[i];
            for (int j = i+1; j < arr.length; j++) {
                if(arr[j] == currItem){
                        return false;
                    }
            }
        }

        return true;
    }

    static double findAverage(int [] integers) {
        double sum = 0 ;
        for (int i = 0; i < integers.length; i++) {
            sum += integers[i];
        }

        return sum/integers.length;
    }

    static int[] lowestAverage(int[][] arr) {
        double avg = 0 , minAvg = Integer.MAX_VALUE;
        int minAvgArr[] = arr[0];
        for (int i = 0; i < arr.length; i++) {
            avg = 0;
            for (int j = 0 ; j < arr[i].length ; j++){
                avg+=arr[i][j];
            }
            avg /= arr[i].length;
            if(avg < minAvg) {
                minAvg = avg;
                minAvgArr = arr[i];
            }

        }
        return minAvgArr;
    }
    public static void main(String[] args) {
        int xRoll[] = roll(4);
            System.out.println(Arrays.toString(xRoll));

        int x[] = {1,2,3,4,44,5,44};
        System.out.println(containsDuplicates(x));
        System.out.println(findAverage(x));

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int xx[] = lowestAverage(weeklyMonthTemperatures);
        System.out.println(Arrays.toString(xx));

    }
}
