/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
     int linter (String path) throws IOException{
        Scanner sc = new Scanner(new BufferedReader(new FileReader(path)));
        int errorLine = 0, error = 0;
        String currentLine = "";
        try {
            while (sc.hasNext()) {
                currentLine = sc.nextLine();
                if(!currentLine.endsWith(";") && !currentLine.isEmpty() &&
                        !currentLine.endsWith("{")
                        &&
                        !currentLine.endsWith("}") &&
                        !currentLine.contains("if") &&
                        !currentLine.contains("else")
                ) {
                    error++;
                    System.out.println(++errorLine + " Missing semicolon.");
                }
                else {
                    errorLine++;
                }
            }
        }

        catch (Exception e) {
            System.out.println(e);
        }

        finally {
            sc.close();
        }

        return error;
    }
    public static void main(String[] args) throws IOException {
        Path path = Paths.get("C:\\Users\\mmohi\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        new App().linter(path.toString());
        System.out.println(path.toString());
    }

    public Object getGreeting() {
        return new String("Hello");
    }
}
